# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'armrgpipe-conn'
    subscriptionId: 'e3133bc0-5aab-42bd-b381-5860fe695537'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'armrgpipe-rg'
    location: 'West US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/gbryant1/armrgpipe/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName armrgpipe'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'